title: "The Sonic Verdict"
description: "Deep dives, hot takes, and sonic truth — a blog for music lovers."
url: "https://justhal22.github.io"
baseurl: "/The-Sonic-Verdict"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: "/:categories/:title/"
paginate: 6
paginate_path: "/page:num/"
markdown: kramdown
highlighter: rouge

author:
  name: "JustHal"
  email: "halbrookes22@gmail.com"
  links:
    - title: "GitHub"
      url: "https://github.com/justhal22"
      icon: "fab fa-github"
    - title: "Twitter"
      url: "https://twitter.com/sonicverdict"
      icon: "fab fa-twitter"
    - title: "Email"
      url: "mailto:halbrookes22@gmail.com"
      icon: "fas fa-envelope"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "JustHal"
      share: true
      comments: true

