# Site identity
title: "The Sonic Verdict"
description: "Deep dives, hot takes, and sonic truth — a blog for music lovers."
url: "https://justhal22.github.io"
baseurl: "/The-Sonic-Verdict" # GitHub Pages repo name

# Visuals
logo: logo: /assets/images/logo.png

# Theme & build
theme: minima
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Pagination
paginate: 6
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Author info
author:
  name: "JustHal"
  email: "halbrookes22@gmail.com"
  links:
    - title: "GitHub"
      url: "https://github.com/justhal22"
      icon: "fab fa-github"
    - title: "Twitter"
      url: "https://twitter.com/sonicverdict"
      icon: "fab fa-twitter"
    - title: "Email"
      url: "mailto:halbrookes22@gmail.com"
      icon: "fas fa-envelope"

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "JustHal"
      
